config/routes.rb
Rails.application.routes.draw do
  get 'nflplayers/index'

  get 'nflplayers/show'

  get 'nflteams/index'

  get 'nflteams/show'

  get 'nfldata/index'

  root 'nfldata#index'

  resources :nflgames

  resources :nflteams

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nflgame.rb
class Nflgame < ApplicationRecord
  belongs_to :nflweek
end

app/models/nflweek.rb
class Nflweek < ApplicationRecord
  has_many :nflgames
end

app/controllers/application_controller.rb
require 'open-uri'

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nfldata_controller.rb
require 'open-uri'

class NfldataController < ApplicationController
  def index
  end

  def show

  end

  def current_week_schedule

    current_week_games_path = "liveupdate/scorestrip/ss.xml"
    arbitrary_week_games_base_path = "ajax/scorestrip?"
    attr_season = "season="
    attr_seasonType = "seasonType="
    attr_week = "week="

    game_data_path = "liveupdate/game-center/"
    url_end = "_gtd.json"

    data = open("http://www.nfl.com/liveupdate/scorestrip/ss.xml")

    current_week_data = Hash.from_xml(data)

    @gms = current_week_data['ss']['gms']
    @g = @gms['g']

    current_week = Nflweek.create(w: @gms['w'], y: @gms['y'], t: @gms['t'], gd: @gms['gd'], bph: @gms['bph'])

    @g.each do |g|
      hteam = Nflteam.find_by(abbr: g['h'])
      vteam = Nflteam.find_by(abbr: g['v'])
      Nflgame.create(
        eid: g['eid'],
        gsis: g['gsis'],
        d: g['d'],
        t: g['t'],
        q: g['q'],
        h: hteam.id,
        hs: g['hs'],
        v: vteam.id,
        vs: g['vs'],
        rz: g['rz'],
        gt: g['gt'],
        nflweek_id: current_week.id)
    end
  end

  def createNflTeams(teams)
    teams.each do |t|
      Nflteam.create(
        abbr: t.abbr,
        nn: t.nn,
        wins: t.wins,
        losses: t.losses)
    end
  end

  def countNflTeams
    return count(Nflteam.all)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nfldata_helper.rb
module NfldataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mordecai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nfldata/index.html.erb
<h2>All games in DB</h2>
<table>
  <tr>
    <th>eid</th>
    <th>season</th>
    <th>type</th>
    <th>week</th>
    <th>away</th>
    <th>home</th>
  </tr>

  <% Nflgame.order("eid ASC").all.each do |game| %>
  <tr>
    <td><%= link_to game.eid, nflgame_path(game) %></td>
    <% week = Nflweek.find(game.nflweek_id) %>
    <% h = Nflteam.find(game.h) %>
    <% v = Nflteam.find(game.v) %>
    <td><%= week.y %></td>
    <td><%= game.gt %></td>
    <td><%= week.w %></td>
    <% vteam = Nflteam.find_by(abbr: v.abbr) %>
    <td><%= link_to v.abbr, nflteam_path(vteam) %></td>
    <% hteam = Nflteam.find_by(abbr: h.abbr) %>
    <td><%= link_to h.abbr, nflteam_path(hteam) %></td>
  </tr>
  <% end %>
</table>